### ISSUE TITLE
Namespace packaging

### ISSUE THREAD

**Issue by oesteban** [nipreps/synthstrip#1]
shouldn't this:

https://github.com/nipreps/synthstrip/blob/dcc89bee00275374daeeaf6007ba90a35a4bdbca/pyproject.toml#L6

be

```toml
 name = "nipreps-synthstrip"
```

as per https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages?

And then also (https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-namespace-packages):

```toml
[tool.setuptools.packages.find]
where = ["nipreps"]
```
